# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Noah's Log
email: noah.bieler@gmx.ch
description: > # this means to ignore newlines until "baseurl:"
    Noah's log where all the cool things are dumped and stored for 
    future generations.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: NoahBieler
github_username:  bielern

# Build settings
markdown: kramdown
